Fixing missing </div> caught by validator.w3.org
The errors given were:
Error: End tag aside seen, but there were open elements.
Error: Unclosed element div.

They were caused by a missing </div> just inside an <aside> block.